### ISSUE TITLE
Issue with the Axe of the Stream - Thaumcraft 4.2.2.1 

### ISSUE THREAD

**Issue by Slockerbie** [Azanor/thaumcraft#1845]
When I use the Axe of the Stream to cut down trees, the logs are destroyed rather than placed into my inventory or dropping onto the ground. Using shift-left click chops single logs normally i.e. useable logs drop, whereas left clicking only appears to destroy the logs.

**Comment by Dream-Master** [comment]
Why not using 4.2.3.5?

**Comment by Slockerbie** [comment]
It is part of a mod pack that I am using. However, you do have a good point. I will try updating the pack and see if the issue persists.

**Comment by Dream-Master** [comment]
Because 4.2.3.5 is the lasted version and maybe it is fixed. Chnaging this Version in the Modpack i would try.

**Comment by Slockerbie** [comment]
Tried changing to the latest version of the pack and unfortunately the problem persists. I tried making a new axe as well as bringing one in through creative mode. Both of these had the same issue. It is a shame, the Axe of the Stream is one of my favorite tools in Thaumcraft.

**Comment by Dream-Master** [comment]
Which Mods the pack have?

**Comment by Slockerbie** [comment]
This is a full list of the mods and current versions.

Minecraft Forge	10.13.2.1277
Apache Commons Codec	1.9
Apache Commons Compress library	1.8.1
Baubles	1.0.1.10
CodeChickenLib	1.1.1.110
ForgeMultipart	1.1.1.320
MrTJPCore	1.0.3.5
Admin Commands Toolbox	0.0.2a
Advanced Generators	0.9.6.27
AOBD	2.3.5
Applied Energistics 2	rv2-beta-7
Archimedes' Ships	1.7.1
Aroma1997Core	1.0.2.13
Aroma1997s Dimensional World	1.0.2.16
Ars Magica 2	1.4.0.006
AsieLib	0.3.4
AutoPackager	1.5.3
Balkon's WeaponMod	1.14.3
BdLib	1.5.1.32
BetterChests	1.1.1.8
BiblioCraft	1.9.2
BiblioWoods Biomes O'Plenty Edition	1.9
BiblioWoods Natura Edition	1.5
Big Reactors	0.4.1A2
Biomes O' Plenty	2.1.0.1004
Blood Magic	1.3.0a-1
Botania	1.3-149
Buildcraft	6.2.6
Carpenter's Blocks	3.3.4.2
Chisel 2	2.2.1
CodeChickenCore	1.0.4.29
CoFH Framework	3.0.0B9-75
Compact Machines	1.13
Computronics	1.3.2
CookieCore	1.3.0
Crafting Pillars	1.6.1
Dense Ores	1.5
Easy Crafting	2.0.1.16
Enchanting Plus	3.0.2-d
Enchiridion	1.2b
Ender IO	2.2.6.317
Ender Storage	1.4.5.27
EnderTech	0.3.0.353
EnhancedPortals 3	3.0.9
ExtraTiC	1.0.3
Extra Utilities	1.2.1
Factorization	0.8.88.7
Flaxbeard's Steam Power	0.27.3
FLORA	1.0.5
Forbidden Magic	0.552
FoxLib	0.6.0
Funky Locomotion	beta-4
FZAddons	1.0.0
Galacticraft Core	3.0.6.250
Galacticraft Planets	3.0.6.250
GrowthCraft Apples	2.1.0
GrowthCraft Bamboo	2.1.0
GrowthCraft Bees	2.1.0
GrowthCraft Core: Cellar	2.1.0a
GrowthCraft Core	2.1.0a
GrowthCraft Fishtrap	2.1.0a
GrowthCraft Grapes	2.1.0
GrowthCraft Hops	2.1.0
GrowthCraft Rice	2.1.0a
Hardcore Ender Expansion	1.6.7
Hats	4.0.1
HatStand	4.0.0
Headcrumbs	1.3.0
iChunUtil	4.1.3
INpureCore	1.0.0B2-4
Iron Chest	6.0.49.733
Java 7 Checker	1.1
Liquid Dirt	1.3
LunatriusCore	1.1.2.18
MalisisCore	0.10.3
MalisisDoors	1.3.3
Mantle	0.3.2
Mariculture	1.2.3d
Metallurgy 4	4.0.6.80
Metallurgy Core	4.0.4.18
Modular Force Field System	4.1.0.32
Micdoodle8 Core	3.0.6.250
Minechem	5.0.5.348
MineFactory Reloaded	2.8.0RC6-21
MineMenu	1.2.0.B44
MineTweaker 3	3.0.9C
MobiusCore	1.2.3
ModTweaker	0.6-22
Morph	0.9.1 beta
Natura	2.2.0.1
NEI Addons	1.12.3.11
NEI Integration	1.0.3
Nether Ores	2.3.0RC4-8
NotEnoughItems	1.0.4.83
No More Recipe Conflict	0.2
OpenBlocks	1.3
OpenComputers	1.4.3.21 beta 1
OpenMods Lib	0.6
Pam's Harvestcraft	1.7.10f
PneumaticCraft	1.5.1-49
Practicalities	0.5.0
Pressure Pipes	1.0.1.48
Project Red: Base	4.5.7.58
Project Red: Compat	4.5.7.58
Project Red: Exploration	4.5.7.58
Project Red: Illumination	4.5.7.58
Project Red: Integration	4.5.7.58
Railcraft	9.4.0.0
Random Things 2	2.2.3
Redstone Arsenal	1.1.0RC1-23
Redstone Paste	1.6.2
Refined Relocation	1.0.7d
Resonant Engine	2.0.0.130
Roguelike Dungeons Mod	1.3.5
Sanguimancy	1.1.8-4
Simply Jetpacks	1.3.2
SolarFlux	0.5
Soul Shards: Reborn	RC3
Special Mobs	3.0.3
Stackie	1.5.1.30
Steve's Carts 2	2.0.0.b18
Steve's Factory Manager	A93
Steve's Workshop	0.5.1
Super Crafting Frame	1.7.10.1
Tails	1.2.3
Tinkers' Construct	1.8.1
Tinkers' Mechworks	0.2.10
Tinkers' Steelworks	1.0.6
Thaumcraft 4	4.2.3.5
Thaumic Exploration	1.1-34
Thaumic Tinkerer	2.5-162
Thermal Expansion	4.0.0B8-23
Thermal Foundation	1.0.0RC1-17
The Twilight Forest	2.3.2
TooMuchRain	1.0.0-b5
Universal Electricity	4.0.0.81
WAILA	1.5.7a
WAWLA	1.1.0
Witchery	0.21.2
WR-CBE	1.4.1.9
Ztones	2.2
Damage Indicators	3.2.0
Inventory Tweaks	1.59-dev-156
JourneyMap	5.0.1
LiteLoader	1.7.10
Not Enough Keys	1.0.0b27
Shatter	4.0.0
TiCTooltips	1.2.0
WAILA Harvestability	1.1.1
Zan's Minimap	1.2.3
Morpheus	1.5.26
Animation API	1.2.4
FastCraft	1.12
LiteLoader Settings	1.0.0
MineTweaker Scripts	1.0.4
Zans Settings	1.0.0

**Comment by Dream-Master** [comment]
The best thing is to try it only with thaumcraft and minecraft to see if this is a thaumcraft bug.
I see a very old Forge version and Morpheus is only a server mod. To many mods to look for errors. Try to add mods and look if it happen and which mod cause it.

**Comment by Slockerbie** [comment]
Launched with only Minecraft and Thaumcraft. it looks like there is a conflict somewhere. Might be time to consider building my own pack as I really do not relish the prospect of stripping out 100+ mods to identify the problem. Thank you for the help!

If anyone else has experienced this problem with The Crackpack on the ATLauncher, I would love to know if there is a simple solution.

**Comment by Slockerbie** [comment]
Did some more searching and found a thread covering a similar problem. Looks like Stackie needed to be updated in order to avoid it conflicting.
